<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Konekt_Cms_Catalog_Model_Migration_Version0001 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('productstate', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('product', 'productstate_id', 'integer', '8', array(
             ));
        $this->addColumn('product_version', 'productstate_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('productstate');
        $this->removeColumn('product', 'productstate_id');
        $this->removeColumn('product_version', 'productstate_id');
    }
}
