# Konekt Framework local configuration file
# Please note to use the following replacement table for db connection values:
#  (in case dbhost, database, username, password contains any of them
#  ------------------------
#	Character	-> Replacement
#  ========================
#      :           %3a
#      /           %2f
#      @           %40
#      +           %2b
#      (           %28
#      )           %29
#      ?           %3f
#      =           %3d
#      &           %26
#  ========================
core:
   dateFormat: "%Y.%m.%d"
   dateTimeFormat: "%Y.%m.%d %H:%M"
   contentDir: media
   cacheDir: cache
   modules:
      Konekt_Core:
      Konekt_User:
      Konekt_Comment:
      Konekt_Blog:
      Konekt_Image:
      Konekt_Catalog:
      Artkonekt_Delikates:
   db:
      host: localhost
      database: delides
      username: delikates
      password: S3x0nTh3B34ch
      type: mysql
konekt:
   image:
      directory: images
      defaultWidth: 850
      defaultHeight: 550
      defaultThumbnailWidth: 170
      defaultThumbnailHeight: 128
artkonekt:
   delikates:
      blogs:
         hu: 1
         ro: 2 
