detect_relations: true
options:
  type: INNODB
  collate: utf8_hungarian_ci
  charset: utf8

User:
   columns:
      Email: string(255)
      Password: string(511)
      Firstname: string(100)
      Lastname: string(100)
      Phone: string(64)
      Salutation: string(50)
      Openid: string(255)
      Enabled: bool
   indexes:
      Email_index:
         fields: [Email]
         type: unique
   actAs:
      Timestampable:
         
Role:
   columns:
      Name: string(255)

UserRole:
   columns:
      User_id:
         type: integer
         primary: true
      Role_id:
         type: integer
         primary: true

