<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Konekt_Cms_Image_Model_Migration_Version0001 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('image', 'url', 'string', '768', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('image', 'url');
    }
}
