detect_relations: true
options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8

User:
   columns:
  
Comment:
   columns:
      Parent_id: integer
      Entity: string(100)
      User_id: integer
      Name: string(255)
      Email: string(255)
      Useragent: string(128)
      Content: clob
      Onhold: boolean
      Private: boolean
   indexes:
      Entity_Parent_id_index:
         fields: [Entity, Parent_id]
   actAs:
      Timestampable:

