detect_relations: true
options:
  type: INNODB
  collate: utf8_hungarian_ci
  charset: utf8


Language:
   columns:
      Code:
         type: string(2)
      Namenative:
         type: string(100)
      Nameenglish:
         type: string(100)
         
Country:
   columns:
      Code2:
         type: string(2)
      Code3:
         type: string(3)
      Namenative:
         type: string(100)
      Nameenglish:
         type: string(100)
         
Currency:
   columns:
      Code: string(3)
      Symbol: string(7)
      Singural: string(24)
      Plural: string(24)
      Roundto: int

