<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Konekt_Cms_Blog_Model_Migration_Version0001 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('blog', 'imagegroup', 'string', '64', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('blog', 'imagegroup');
    }
}
